### ISSUE TITLE
mingw32-i386-system

### ISSUE THREAD

**Issue by hitchhikr** [aros-development-team/AROS#567] opened 2021-07-27 14:15 UTC
"mingw32-i386-system" (2021-07-27) just displays:

[Bootstrap] RAM memory block allocated: 043A0000 - 083A0000 (67108864 bytes)

and sits there forever.

(I think this distribution have been broken for years).

**Comment by Kalamatee** [comment] 2021-07-27 19:55
have you tried booting with sysdebug=all?

**Comment by hitchhikr** [comment] 2021-07-31 00:26
Yes, lots of debug infos but no particular error message.
Here are the last messages of the log :
http://franck.charlet.pagesperso-orange.fr/temp/aros_mingw32_debug.txt

**Comment by Kalamatee** [comment] 2022-03-28 13:24
@hitchhikr sorry for the delay looking at this - but I have been a bit busy since last summer.

I have looked at your debug and tried here, and from the output AROS is clearly running - however it has not created any displays. I have enabled debug in WinGDI and think I have located the problem code;

After launching GDIBase->displaynum = 0;
AddDisplays() then uses "old = displaynum - 1" for a loop - effectively making it never run the loop (old == 4294967295, so the check of "old < num" fails).

I have committed a change to this, and issued a new build. Please check and see if it now opens the display (Though, I cant see how this has ever worked in the current state).

**Comment by Kalamatee** [comment] 2022-03-28 19:34
Found another "bug" in the bitmap class that prevented it working (it used an operation that doesn't support the number of attributes used). Tested and confirmed booting to Wanderer desktop.

**Closed by Kalamatee** 2022-03-28 19:34 UTC
Labels: bug
